version: 0.2
phases:
  install:
    command:
    - echo "Installing Dependencies..." && sleep 3
    - echo "Installation Finished"
  build:
    commands:
    - echo "Zipping project files..."
    - zip deployment_package.zip lambda_function.py
    - echo "Testing ..." && sleep 3
    - echo "Test Finished. => Coverage 100%"
    - echo "Check your test report at https://randomurl.com/test-result/build?<commit>"
  post_build:
    commands:
    - echo "Updating lambda Function..."
    - aws lambda update-function-code --function-name get-pdf-size --zip-file fileb://deployment_package.zip
    - echo "Lambda function updated successful"
